export const mockProducts = [
  {
    id: "prod_LvJjoPbdenle0n",
    created: 1717165697,
    updated: 1717165697,
    active: true,
    permalink: "34obJq",
    name: "K380 Multi-Device Bluetooth  Keyboard",
    description: "<p>Minimalist keyboard for computers, tablets and phones</p>",
    price: {
      raw: 49.99,
      formatted: "49.99",
      formatted_with_symbol: "£49.99",
      formatted_with_code: "49.99 GIP",
    },
    inventory: {
      managed: true,
      available: 128,
    },
    sku: null,
    sort_order: 0,
    seo: {
      title: null,
      description: null,
    },
    thank_you_url: null,
    meta: null,
    conditionals: {
      is_active: true,
      is_tax_exempt: false,
      is_pay_what_you_want: false,
      is_inventory_managed: true,
      is_sold_out: false,
      has_digital_delivery: false,
      has_physical_delivery: false,
      has_images: true,
      collects_fullname: false,
      collects_shipping_address: false,
      collects_billing_address: false,
      collects_extra_fields: false,
    },
    is: {
      active: true,
      tax_exempt: false,
      pay_what_you_want: false,
      inventory_managed: true,
      sold_out: false,
    },
    has: {
      digital_delivery: false,
      physical_delivery: false,
      images: true,
    },
    collects: {
      fullname: false,
      shipping_address: false,
      billing_address: false,
      extra_fields: false,
    },
    checkout_url: {
      checkout: "https://checkout.chec.io/34obJq?checkout=true",
      display: "https://checkout.chec.io/34obJq",
    },
    categories: [],
    image: {
      id: "ast_mOVKl4YxVLwprR",
      url: "https://cdn.chec.io/merchants/57291/assets/yayFIma1y1bF4Q7Y|k380-sand-gallery-1-ch.webp",
      description: null,
      is_image: true,
      filename: "k380-sand-gallery-1-ch.webp",
      file_size: 86908,
      file_extension: "webp",
      image_dimensions: {
        width: 1384,
        height: 1038,
      },
      meta: [],
      created_at: 1717165642,
      updated_at: 1717165644,
    },
  },
  {
    id: "prod_BkyN5YQROL50b6",
    created: 1717403809,
    updated: 1717403809,
    active: true,
    permalink: "ZejTDX",
    name: "MX Master 3S For Mac",
    description: "<p>Performance Wireless Mouse</p>",
    price: {
      raw: 94.99,
      formatted: "94.99",
      formatted_with_symbol: "£94.99",
      formatted_with_code: "94.99 GIP",
    },
    inventory: {
      managed: true,
      available: 50,
    },
    sku: null,
    sort_order: 0,
    seo: {
      title: null,
      description: null,
    },
    thank_you_url: null,
    meta: null,
    conditionals: {
      is_active: true,
      is_tax_exempt: false,
      is_pay_what_you_want: false,
      is_inventory_managed: true,
      is_sold_out: false,
      has_digital_delivery: false,
      has_physical_delivery: false,
      has_images: true,
      collects_fullname: false,
      collects_shipping_address: false,
      collects_billing_address: false,
      collects_extra_fields: false,
    },
    is: {
      active: true,
      tax_exempt: false,
      pay_what_you_want: false,
      inventory_managed: true,
      sold_out: false,
    },
    has: {
      digital_delivery: false,
      physical_delivery: false,
      images: true,
    },
    collects: {
      fullname: false,
      shipping_address: false,
      billing_address: false,
      extra_fields: false,
    },
    checkout_url: {
      checkout: "https://checkout.chec.io/ZejTDX?checkout=true",
      display: "https://checkout.chec.io/ZejTDX",
    },
    categories: [
      {
        id: "cat_ZM8X5neNNopv4q",
        slug: "mice",
        name: "Mice",
      },
    ],
    image: {
      id: "ast_Op1YoV1egVwXLv",
      url: "https://cdn.chec.io/merchants/57291/assets/hW6V3DD7OAUZQuuC|mx-master-3s-for-mac-mouse-top-view-pale-grey.webp",
      description: null,
      is_image: true,
      filename: "mx-master-3s-for-mac-mouse-top-view-pale-grey.webp",
      file_size: 31332,
      file_extension: "webp",
      image_dimensions: {
        width: 1384,
        height: 1038,
      },
      meta: [],
      created_at: 1717403801,
      updated_at: 1717403803,
    },
  },
  {
    id: "prod_p6dP5gGPLg5n7k",
    created: 1717404637,
    updated: 1717404648,
    active: true,
    permalink: "yyIjQt",
    name: "Brio 500",
    description:
      "<p></p><p>Full HD 1080p webcam with light correction, auto-framing, and Show Mode</p>",
    price: {
      raw: 129,
      formatted: "129.00",
      formatted_with_symbol: "£129.00",
      formatted_with_code: "129.00 GIP",
    },
    inventory: {
      managed: true,
      available: 100,
    },
    sku: null,
    sort_order: 0,
    seo: {
      title: null,
      description: null,
    },
    thank_you_url: null,
    meta: null,
    conditionals: {
      is_active: true,
      is_tax_exempt: false,
      is_pay_what_you_want: false,
      is_inventory_managed: true,
      is_sold_out: false,
      has_digital_delivery: false,
      has_physical_delivery: false,
      has_images: true,
      collects_fullname: false,
      collects_shipping_address: false,
      collects_billing_address: false,
      collects_extra_fields: false,
    },
    is: {
      active: true,
      tax_exempt: false,
      pay_what_you_want: false,
      inventory_managed: true,
      sold_out: false,
    },
    has: {
      digital_delivery: false,
      physical_delivery: false,
      images: true,
    },
    collects: {
      fullname: false,
      shipping_address: false,
      billing_address: false,
      extra_fields: false,
    },
    checkout_url: {
      checkout: "https://checkout.chec.io/yyIjQt?checkout=true",
      display: "https://checkout.chec.io/yyIjQt",
    },
    categories: [
      {
        id: "cat_gvRjwOpWBo4mNL",
        slug: "webcams-audio",
        name: "Webcams & Audio",
      },
    ],
    image: {
      id: "ast_bWZ3l81mBvwkpE",
      url: "https://cdn.chec.io/merchants/57291/assets/NpldO9b8JgfZhAA0|brio-500-gallery-offwhite-1.webp",
      description: null,
      is_image: true,
      filename: "brio-500-gallery-offwhite-1.webp",
      file_size: 77414,
      file_extension: "webp",
      image_dimensions: {
        width: 1384,
        height: 1038,
      },
      meta: [],
      created_at: 1717404632,
      updated_at: 1717404634,
    },
  },
  {
    id: "prod_G6kVw7qjm252eD",
    created: 1717404815,
    updated: 1717404815,
    active: true,
    permalink: "2dzDHI",
    name: "Logitech Crayon (USB-C)",
    description:
      "<p>Pixel-precise digital pencil for all iPad models (2018 and later). Rechargeable via USB-C.</p>",
    price: {
      raw: 69.99,
      formatted: "69.99",
      formatted_with_symbol: "£69.99",
      formatted_with_code: "69.99 GIP",
    },
    inventory: {
      managed: true,
      available: 100,
    },
    sku: null,
    sort_order: 0,
    seo: {
      title: null,
      description: null,
    },
    thank_you_url: null,
    meta: null,
    conditionals: {
      is_active: true,
      is_tax_exempt: false,
      is_pay_what_you_want: false,
      is_inventory_managed: true,
      is_sold_out: false,
      has_digital_delivery: false,
      has_physical_delivery: false,
      has_images: true,
      collects_fullname: false,
      collects_shipping_address: false,
      collects_billing_address: false,
      collects_extra_fields: false,
    },
    is: {
      active: true,
      tax_exempt: false,
      pay_what_you_want: false,
      inventory_managed: true,
      sold_out: false,
    },
    has: {
      digital_delivery: false,
      physical_delivery: false,
      images: true,
    },
    collects: {
      fullname: false,
      shipping_address: false,
      billing_address: false,
      extra_fields: false,
    },
    checkout_url: {
      checkout: "https://checkout.chec.io/2dzDHI?checkout=true",
      display: "https://checkout.chec.io/2dzDHI",
    },
    categories: [
      {
        id: "cat_N7GKwb6P4w3EX4",
        slug: "mobile-solutions",
        name: "Mobile Solutions",
      },
    ],
    image: {
      id: "ast_8XxzoBOLgZ5PQA",
      url: "https://cdn.chec.io/merchants/57291/assets/rHYhSHi5O4KEYs9G|crayon-gallery2.webp",
      description: null,
      is_image: true,
      filename: "crayon-gallery2.webp",
      file_size: 11736,
      file_extension: "webp",
      image_dimensions: {
        width: 1384,
        height: 1038,
      },
      meta: [],
      created_at: 1717404784,
      updated_at: 1717404786,
    },
  },
];

export const mockProduct = {
  id: "prod_LvJjoPbdenle0n",
  created: 1717165697,
  updated: 1717165697,
  active: true,
  permalink: "34obJq",
  name: "K380 Multi-Device Bluetooth  Keyboard",
  description: "<p>Minimalist keyboard for computers, tablets and phones</p>",
  price: {
    raw: 49.99,
    formatted: "49.99",
    formatted_with_symbol: "£49.99",
    formatted_with_code: "49.99 GIP",
  },
  inventory: {
    managed: true,
    available: 128,
  },
  sku: null,
  sort_order: 0,
  seo: {
    title: null,
    description: null,
  },
  thank_you_url: null,
  meta: null,
  conditionals: {
    is_active: true,
    is_tax_exempt: false,
    is_pay_what_you_want: false,
    is_inventory_managed: true,
    is_sold_out: false,
    has_digital_delivery: false,
    has_physical_delivery: false,
    has_images: true,
    collects_fullname: false,
    collects_shipping_address: false,
    collects_billing_address: false,
    collects_extra_fields: false,
  },
  is: {
    active: true,
    tax_exempt: false,
    pay_what_you_want: false,
    inventory_managed: true,
    sold_out: false,
  },
  has: {
    digital_delivery: false,
    physical_delivery: false,
    images: true,
  },
  collects: {
    fullname: false,
    shipping_address: false,
    billing_address: false,
    extra_fields: false,
  },
  checkout_url: {
    checkout: "https://checkout.chec.io/34obJq?checkout=true",
    display: "https://checkout.chec.io/34obJq",
  },
  categories: [],
  image: {
    id: "ast_mOVKl4YxVLwprR",
    url: "https://cdn.chec.io/merchants/57291/assets/yayFIma1y1bF4Q7Y|k380-sand-gallery-1-ch.webp",
    description: null,
    is_image: true,
    filename: "k380-sand-gallery-1-ch.webp",
    file_size: 86908,
    file_extension: "webp",
    image_dimensions: {
      width: 1384,
      height: 1038,
    },
    meta: [],
    created_at: 1717165642,
    updated_at: 1717165644,
  },
};
