export const mockCategories = [
  {
    id: "cat_N7GKwb6P4w3EX4",
    parent_id: null,
    slug: "mobile-solutions",
    name: "Mobile Solutions",
    description: null,
    products: 1,
    created: 1717403536,
    updated: 1717403536,
    meta: null,
    assets: [],
    children: [],
  },
  {
    id: "cat_gvRjwOpWBo4mNL",
    parent_id: null,
    slug: "webcams-audio",
    name: "Webcams & Audio",
    description: null,
    products: 1,
    created: 1717403507,
    updated: 1717403507,
    meta: null,
    assets: [],
    children: [],
  },
  {
    id: "cat_ZM8X5neNNopv4q",
    parent_id: null,
    slug: "mice",
    name: "Mice",
    description: null,
    products: 1,
    created: 1717403451,
    updated: 1717403451,
    meta: null,
    assets: [],
    children: [],
  },
  {
    id: "cat_mOVKl4RWroprRP",
    parent_id: null,
    slug: "keyboards",
    name: "Keyboards",
    description: null,
    products: 0,
    created: 1717403377,
    updated: 1717403377,
    meta: null,
    assets: [],
    children: [],
  },
];
